adfinis/ember-validated-form

.gitignore, addon/components/validated-input/template.hbs, tests/dummy/app/components/color-component.js, tests/dummy/app/components/favorite-colors-component.js, tests/dummy/app/controllers/index.js, tests/dummy/app/templates/components/color-component.hbs, tests/dummy/app/templates/components/favorite-colors-component.hbs, tests/dummy/app/templates/index.hbs, tests/dummy/app/validations/user.js
There is a stackoverflow [question](http://stackoverflow.com/questions/42921997/using-ember-with-maskedinput-and-validated-form) regarding your addon. The developer there is willing to add a masked-input into your add-on. However; as far as I can see your support for custom components need a little bit of enhancement. Hence I have already created an [issue](https://github.com/adfinis-sygroup/ember-validated-form/issues/16) for what I mean. This is the pull request regarding that issue. I have already changed `validated-input` to be used in block-form. I also included two custom components (a custom color pick component and a checkbox) usage in block-form so as to demonstrate what I mean. If you accept the pull request I can also improve the documentation regarding the usage of custom …
=> support for much better custom component usage

bower.json, package.json
Upgraded an existing project from ember 2.10.0 to 2.12.0, due to https://github.com/cibernox/ember-power-select/issues/877 .
Having done the upgrade, on ember build, see a warning that ember-cli-babel, plus ember-validated-form addons should be under dependencies, not devDependencies.
Pull request is the result of upgrading the package to 2.12.0, and making the changes recommended by the warning.
Think the warning is caused by a change to ember-cli-babel at ember version 2.12.0.
Tests pass, demo builds and runs as previously.
=> Upgrade to ember 2.12.0

addon/components/validated-input/component.js, tests/dummy/app/templates/index.hbs
Define on the form field if it should show a required star * or not. 
This does not overwrite other validation settings from the field.
=> Required (star) as an form field flag

.gitignore, README.md, addon/components/validated-input/template.hbs, tests/integration/components/validated-form/component-test.js
Hi folks! 
Thanks for all your work on this package! It's lovely and usable.
I needed to use i18n-translated labels within radio groups. Instead of pre-translating them before creating the Options hash, I refactored the radio group to yield out for the label content of individual radios when used in block form.
This PR includes tests & some changes to the README to describe this usage.
Please let me know if you see spots for improvement, or if you have any questions? PS this is my work GitHub account, I'm at @jakemoves for other work.
Best regards,
Jacob
=> Support block form usage of radioGroups

addon/templates/components/validated-input.hbs
Without this fix we get an error when "promptIsSelectable" is not
specified and the submit button is pressed. This is due to the fact
that ember-one-way-select is updating "promptIsSelectable" inside
"didReceiveAttrs" to false when it's blank.
This issue should maybe be reported to ember-one-way-components, but I
didn't manage to create a small reproduction :(
=> Fix "modified twice in a single render" issue

README.md, addon/components/validated-form.js, addon/components/validated-input.js, addon/templates/components/validated-form.hbs, tests/integration/components/validated-form-test.js
Many form implementations don't run any validations until the first time the user tries to submit the form, so this option allows that behavior.
=> Add a validateBeforeSubmit option

addon/components/validated-form.js, tests/integration/components/validated-form-test.js, yarn.lock
If were form is removed from the DOM during the submit operation, it would throw a `cannot set property on destroyed object` when trying to clear the loading flag. Switching to an `ember-concurrency` task for the async behavior prevents those kinds of errors, and also allows for (in my opinion) more readable code.
=> Fix for removal from DOM during submit

README.md, addon/components/validated-form.js, tests/integration/components/validated-form-test.js
Passing a task instance directly to on-submit is now no longer supported in favor of using the `perform` helper (`on-submit=(perform myTask)`).
=> Remove deprecated task support

CHANGELOG.md
I'm not completely sure how the update path to 1.0.0 looks. I suppose `changeset` and `changeset-validations` will be removed from `node_modules`. Will the blueprint be automatically installed? If not, we'd probably have to suggest installing the two dependencies manually if they're required?
=> Update CHANGELOG for 1.0.0

tests/dummy/app/snippets/config-bootstrap-v4.js, tests/dummy/config/environment.js
As I was setting up Bootstrap 4, I realized that the error class used in the component is `error`, not `invalid`. The rest of the documentation seems to have it right.
It's used here: https://github.com/adfinis-sygroup/ember-validated-form/blob/e4ee57279af6ff39c1d3e257cace01c8609fbcdc/addon/components/validated-input.js#L35
=> Update bootstrap 4 config error class

addon/templates/components/validated-input.hbs, tests/integration/components/validated-input-test.js
This PR contains two changes in one:
1. Adds tests for the case when `validated-input` is used with a block
2. Passes the generated input id as part of the yielded hash
I can certainly split these up if that is desired, but I wanted to have no 1 while I was working on no 2 to make sure I didn't break anything. Reviewing the commits separately is probably a good idea.
If you choose to provide a block to `validated-input` [as described in the documentation](https://adfinis-sygroup.github.io/ember-validated-form/latest/docs/components/validated-input#custom-input-elements), you can no longer use the generated label because the `for` attribute on that label doesn't point to your input. This means the user doesn't have the functionality of clicking the label to focus the input:
```hbs …
```
=> Yield the generated input id in block form

addon/templates/components/validated-input.hbs
Currently when changing the underlying model, the text shown in the textarea doesn't update.
This solves that.
=> Show updated textarea data when underlying model changes

app/components/validated-input/types/-themes/bootstrap/text.js, app/components/validated-input/types/text.js
This should also fix https://github.com/adfinis-sygroup/ember-validated-form/issues/147 as embroider strictly checks imports which failed at this point.
=> fix: remove unused modules which lead to invalid imports

.github/workflows/test.yml, addon/-private/themed-component.js, addon/components/validated-input.js, addon/templates/components/validated-input.hbs, config/ember-try.js, package.json, tests/dummy/app/templates/docs/customization.md, tests/integration/components/validated-input-test.js, yarn.lock
Previously the computed `_val` did not recompute if `name` was a nested property like `titleObject.de`.
This is solved with using getters. Example twiddle:
https://ember-twiddle.com/9cb7325ea5aa8983b5ea871366014d2d?openFiles=controllers.application%5C.js%2C#docs():
=> fix(validated-input): rewrite to glimmer and support nested changesets

addon/components/validated-input.js
This is a snippet which should have been in #581 but was forgotten :cry:
=> fix(validated-input): use changeset.set if available to preserve state tracking on nested objects

addon/components/validated-input.js, testem.js, tests/integration/components/validated-input-test.js
This fixes a regression introduced with the update to glimmer.
=> fix: call on-update hook correctly

addon/components/validated-input.js, addon/components/validated-input/render.js, addon/components/validated-input/types/-themes/bootstrap/checkbox-group.js, addon/components/validated-input/types/-themes/uikit/checkbox-group.js, addon/components/validated-input/types/checkbox-group.js, addon/templates/components/validated-input/-themes/uikit/render.hbs, addon/templates/components/validated-input/render.hbs, addon/templates/components/validated-input/types/-themes/bootstrap/checkbox-group.hbs, addon/templates/components/validated-input/types/-themes/uikit/checkbox-group.hbs, addon/templates/components/validated-input/types/checkbox-group.hbs, app/components/validated-input/types/-themes/bootstrap/checkbox-group.js, app/components/validated-input/types/-themes/uikit/checkbox-group.js, app/components/validated-input/types/checkbox-group.js, testem.js, tests/dummy/app/templates/docs/components/validated-input.md, tests/integration/components/validated-input-test.js, tests/integration/components/validated-input/types/-themes/bootstrap/checkbox-group-test.js, tests/integration/components/validated-input/types/-themes/uikit/checkbox-group-test.js, tests/integration/components/validated-input/types/checkbox-group-test.js
This implements a group of checkboxes, similar to `radioGroup`.
=> feat: checkbox groups

addon/components/validated-input/types/select.hbs, addon/components/validated-input/types/select.js, tests/integration/components/validated-input/types/select-test.js
Fixes missing interpretation of public API `optionTargetPath` on select inputs.
=> fix(validated-input): interpret optionTargetPath on select

addon/components/validated-form.js, tests/dummy/app/snippets/config-features.js, tests/dummy/app/templates/docs/configuration.md, tests/dummy/config/environment.js
This is a naive implementation for scrolling the first invalid element into view after submit has been triggered.
=> feat: scroll first invalid element into view

addon/components/validated-input/types/select.js
@derrabauke your deprecation message threw another deprecation message because the usage of `deprecate` without `for` is deprecated :rofl:
=> chore(deprecation): fix deprecation when calling deprecate

addon/components/validated-input.hbs, addon/components/validated-input/render.hbs, addon/components/validated-input/types/select.hbs, addon/components/validated-input/types/select.js, tests/dummy/app/templates/docs/components/validated-input.md, tests/dummy/app/templates/docs/migration-v6.md
BREAKING CHANGE: Remove deprecated option `includeBlank` on select inputs.
=> chore(select): remove deprecated option includeBlank on selects

addon/components/validated-input/render.hbs, addon/components/validated-input/render.js, ember-cli-build.js, index.js, package.json, tests/dummy/app/components/favorite-colors.hbs, tests/dummy/app/components/flatpickr-wrapper.hbs, tests/dummy/app/components/x-custom-date.hbs, tests/dummy/app/components/x-custom-render.hbs, tests/dummy/app/snippets/config-custom-date.js, tests/dummy/app/snippets/config-defaults.js, tests/dummy/app/templates/docs/customization.md, tests/integration/components/validated-form-defaults-test.js, yarn.lock
If none is set we just default to the `inputComponent` aka HTML5 picker.
=> feat(input): allow custom date component to be configured

addon/components/validated-button.js, addon/components/validated-form.js
Hello! I ran into an error when using nested fields with the option `scrollErrorIntoView: true`
The addon code evaluates to `document.querySelector('[name=fields.nestedfield]')` and throws the following exception:
`Uncaught DOMException: Failed to execute 'querySelector' on 'Document': 'name=fields.nestedfield' is not a valid selector.`
The fix is to replace `.` with `\\.` in the query selector, i.e `document.querySelector('[name=fields\\.nestedfield]')`
Thank you!
=> fix: scroll error into view with nested key names

addon/components/validated-form.hbs
This allows attributes to be passed to the wrapping form element.
=> feat: allow html attributes to be passed to wrapping form element

tests/dummy/app/templates/docs/customization.md
The [input template at the docs page](https://adfinis.github.io/ember-validated-form/docs/customization#input) shows the wrong template, cause  there is a naming conflict for the snippets with the template of the *Date* paragraph.
=> docs(customization): resolve template naming conflict
