- addon/components/validated-form/component.js
> Make model optional in submit handler

- README.md
- addon/components/validated-form/component.js
- addon/components/validated-form/template.hbs
- package.json
- tests/dummy/app/controllers/index.js
- tests/dummy/app/templates/index.hbs
- tests/dummy/config/environment.js
- tests/unit/components/validated-form-test.js
> Disable submit button while async task is running

- README.md
- addon/components/validated-input/template.hbs
> Add disabled and readonly support

- README.md
@feanor07 This is what i came up with concerning documentation for custom component usage. What do you think?
> Add docs for custom component integration

- addon/components/validated-input/component.js
This allows to work with the given context on-update
> also pass the model to on-update function

- README.md
- addon/components/validated-input/template.hbs
Value option allows to set an initial value for the input field.
> add value option to form input fields

- README.md
- addon/components/validated-form/template.hbs
- addon/components/validated-input/component.js
- make form class customizable
- make error class customizable
- add docs
> Add semantic UI support

- README.md
- addon/templates/components/validated-input.hbs
> add ability to have a selectable prompt from the select dropdown (followup)

- README.md
- tests/dummy/app/components/favorite-colors-component.js
- tests/dummy/app/models/user.js
- tests/dummy/app/templates/index.hbs
This documents the usage of `fi.value` (see #43)
> Improve docs and example on custom components

- addon/templates/components/validated-input.hbs
This is a start for some accessibility improvements still to come
> Add missing IDs

- addon/components/validated-input.js
- addon/templates/components/validated-input.hbs
> Use a unique id for the inputs

- .eslintrc.js
- addon/components/validated-button.js
- addon/components/validated-form.js
- addon/components/validated-input.js
- package.json
- tests/dummy/app/app.js
- tests/dummy/app/components/color-component.js
- tests/dummy/app/components/favorite-colors-component.js
- tests/dummy/app/controllers/index.js
- tests/dummy/app/router.js
- tests/dummy/app/routes/index.js
- tests/helpers/destroy-app.js
- tests/helpers/module-for-acceptance.js
- tests/helpers/start-app.js
- tests/integration/components/validated-form-test.js
> Use new modules API

- addon/templates/components/validated-input.hbs
`rows` and `cols` for `<textarea>` and `autofocus` for `<input>` and `<textarea>`
> Add a couple more input attributes

- package.json
- yarn.lock
Bumped ember-changeset and ember-changeset-validations
> resolve issue 69 update changeset dependencies

- package.json
See https://github.com/poteto/ember-changeset/issues/256
> Pin versions of -changeset and -changeset-validations

- addon/templates/components/validated-input.hbs
- tests/integration/components/validated-form-test.js
> fix: wrap radio, checkbox in span to allow custom styles

- addon/templates/components/validated-input.hbs
- tests/integration/components/validated-form-test.js
> fix: use radio value to expose option key

- README.md
- addon/components/validated-form.js
- addon/templates/components/validated-input.hbs
- tests/integration/components/validated-form-test.js
- tests/integration/components/validated-input-test.js
> feat(validated-input): allow setting autocomplete attribute

- README.md
- addon/components/validated-input.js
- addon/templates/components/validated-input.hbs
- tests/dummy/app/index.html
- tests/dummy/app/templates/index.hbs
- tests/dummy/config/environment.js
- tests/integration/components/validated-form-test.js
- tests/integration/components/validated-input-test.js
* Set valid and invalid class on input component too
* Only set valid class if the value is dirty
* Update README
* Use bootstrap v4 in dummy app
Fixes #99
> Use bootstrap v4 in dummy app

- addon/components/validated-form.js
- package.json
- tests/dummy/app/templates/docs/components/validated-input.md
- yarn.lock
This is not used within the addon anymore in v2.
> Drop dependency on ember-i18n

- addon/templates/components/validated-input.hbs
We could add all properties but I don't want to pollute the namespace/yield too much.
Better to add more properties as they are needed.
> ADD more properties to yield

- .dependabot/config.yml
Auto merges all updates up to minor version of dev dependencies
> chore(ci): change dependabot to auto merge dev dependencies

- .github/workflows/deploy.yml
- .github/workflows/release.yml
Sorry, forgot this in my breaking change pr!
> specify node version in release and deploy workflow

- addon/components/validated-input/types/select.hbs
- addon/components/validated-input/types/select.js
- package.json
- tests/dummy/app/templates/docs/components/validated-input.md
- tests/integration/components/validated-input/types/select-test.js
- yarn.lock
the used one-way-select addon is not actively maintained anymore
> feat(validated-input): replace select component

- addon/components/validated-button.js
- addon/components/validated-form.js
> fix: respect scrollErrorIntoView for validated buttons as well

- addon/components/validated-input.hbs
- addon/components/validated-input/-themes/uikit/render.hbs
- addon/components/validated-input/render.hbs
- tests/dummy/app/templates/docs/components/validated-input.md
- tests/dummy/app/templates/index.hbs
`@prompt` never worked before..
> fix(select): pass prompt argument down to input component

- addon/components/validated-input.hbs
- addon/components/validated-input.js
- addon/components/validated-input/error.hbs
- addon/components/validated-input/hint.hbs
- addon/components/validated-input/types/checkbox-group.hbs
- addon/components/validated-input/types/checkbox.hbs
- addon/components/validated-input/types/radio-group.hbs
- tests/dummy/app/components/permanent-custom-hint.hbs
- tests/integration/components/validated-form-test.js
> feat(a11y): add aria invalid and describedby attributes on validation
